apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-eelpbqhj
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-eelpbqhj:1ebf06c3633e868f10a430f85fe08a58f3ba85e8@sha256:97db38929b159032e89bddc337e5b195e8bf4413988780dde5c951e5469aac46
        name: container-image  
